SuperCoding24/shoppingmall_frontend

- shoppingmall/src/assets/categorydropdown.svg
- shoppingmall/src/components/productList/ProductList.js
> bug: pr충돌 해결

- shoppingmall/src/components/userAccount/Login.js
- shoppingmall/src/components/userAccount/Signup.js
이메일, 휴대폰 번호, 비밀번호 유효성 검사 추가
오타 수정
> 회원가입 유효성 검사 추가
> 오타 수정
> feature : 회원가입 유효성 검사 추가

- shoppingmall/src/components/nav/Nav.js
- shoppingmall/src/components/nav/Navigation.js
- shoppingmall/src/components/userAccount/InputField.js
- shoppingmall/src/components/userAccount/Login.js
- shoppingmall/src/components/userAccount/Signup.js
- shoppingmall/src/components/userAccount/Vaildators.js
- shoppingmall/src/pages/loginPage/LoginPage.js
- shoppingmall/src/pages/signupPage/SignupPage.js
이미지 파일 첨부 및 미리보기,
코드 리팩토링 및 컴포넌트 분할
> refactor/feature : 이미지 파일 첨부 및 미리보기 

- shoppingmall/.gitignore
- shoppingmall/src/components/productDetails/ProductDetail.js
- shoppingmall/src/components/productList/ProducFilter.js
- shoppingmall/src/components/productList/ProductList.js
- shoppingmall/src/style/GlobalStyle.js
쇼핑몰 메인 페이지 UI 수정
Nav 너비에 맞춰서 UI 구성
>
> [fix] 쇼핑몰 목록 페이지 및 상세페이지 UI 레이아웃 수정

- shoppingmall/.gitignore
- shoppingmall/package-lock.json
- shoppingmall/package.json
- shoppingmall/src/components/cart/productList/Count.js
- shoppingmall/src/components/cart/productList/Info.js
- shoppingmall/src/components/cart/productList/OrderAmount.js
- shoppingmall/src/components/cart/productList/ProductList.js
- shoppingmall/src/components/commom/EmptyContentLayout.js
- shoppingmall/src/components/myPage/Info.js
- shoppingmall/src/components/myPage/Profile.js
- shoppingmall/src/components/orderDetails/OrderDetailsList.js
- shoppingmall/src/components/sellpage/ProductArea.js
- shoppingmall/src/hooks/useFetchData.js
- shoppingmall/src/pages/cart/Cart.js
- shoppingmall/src/pages/myPage/MyPage.js
- shoppingmall/src/pages/orderDetails/OrderDetailsPage.js
- shoppingmall/src/style/CommonStyles.js
> ex) #56 
> 장바구니, 마이페이지 api GET 요청 보내서 정보들 가져와서 보여주었습니다. 그 과정에서 필요한 userId는 임의로 넣어서 하였습니다.
그리고 api 요청 부분 커스텀 훅으로 만들었고 GET 메서드가 기본이므로 명시적으로 지정하지 않아도 됩니다.
ex)
```
const [newCartItem, setNewCartItem] = useState({
userId: userId,
productId: 1,
quantity: 2,
price: 1000,
});
const handleAddToCart = () => {
useFetchData(cartUrl, { method: 'POST', body: newCartItem });
};
```
> api 요청에서 loading 부분은 리액트 라이브러리 설치해서 공통 컴포넌르로 분리해서 CommonStyles에 구현해두었습니다.
npm i 해주세요
> .env 파일 만들어서  아래 환경변수들 추가해주세요
```
REACT_APP_API_URL=""
REACT_APP_API_TOKEN=
```
>
> [feat] api GET 요청 (마이페이지, 장바구니) & 커스텀 훅 만들기 & 로딩 스피터 공통 컴포넌트 만들기

- shoppingmall/src/components/nav/Nav.js
- shoppingmall/src/components/userAccount/Login.js
- shoppingmall/src/components/userAccount/Signup.js
- shoppingmall/src/components/userAccount/Vaildators.js
> 로그인, 회원가입 post 요청
> 유효성 검사 형식에 맞게 수정
> nav, 로그인, 회원가입 버튼 디자인 수정
> [fix/design] post요청, 유효성 검사 수정, 버튼 및 너비 수정

- shoppingmall/src/App.js
- shoppingmall/src/components/productwritepage/ProductComponent.js
- shoppingmall/src/components/sellpage/ProductArea.js
- shoppingmall/src/pages/productModifyPage/ProductModifyPage.js
>
#65 
> 
상품 등록 페이지 컴포넌트의 객체, 변수 이름 변경
refactor로 생각했는데 rename이있어 pr은 rename으로 올리겠습니다!!
다음부터 주의하겠습니다.
> [ rename ] 상품 등록 페이지 네이밍 수정

- shoppingmall/src/components/userAccount/Login.js
로컬스토리지에 user_Id 추가
> 로컬스토리지에 user_id 추가
> [feature] 로그인시 userid 로컬스토리지에 추가

- shoppingmall/src/components/userAccount/Login.js
> [fix] 로그인 수정

- shoppingmall/src/components/productwritepage/ProductComponent.js
- shoppingmall/src/components/sellpage/PaginationArea.js
- shoppingmall/src/components/sellpage/ProductArea.js
- shoppingmall/src/pages/sellPage/SellPage.js
…T 구현 / 페이지네이션구현
> 
#91 
> 
토큰유무 파악후 없을시 로그인으로 이동 구현
상품등록시 POST
상품수정 GET, PUT
판매내역 GET 구현
페이지네이션구현
>
> [ feat ] GET, PUT, POST요청 구현 / 페이지네이션 구현

- shoppingmall/src/components/userAccount/Login.js
> [feature] 로그인 엔터키 기능

- shoppingmall/src/components/productDetails/ProductDetail.js
- shoppingmall/src/components/productList/ProductList.js
머지후 productId undefined 문제 해결하였습니다
>
> 머지후 productId undefined 문제 해결

- shoppingmall/src/components/productwritepage/ProductComponent.js
- shoppingmall/src/components/sellpage/ProductArea.js
- shoppingmall/src/pages/productModifyPage/ProductModifyPage.js
- shoppingmall/src/pages/sellPage/SellPage.js
> 
#103 
> 상품 수정페이지 value 가져와서 기입
>
> [ feat ] 상품 수정페이지 value 가져와서 기입

- shoppingmall/src/components/sellpage/PaginationArea.js
- shoppingmall/src/components/sellpage/ProductArea.js
> ex) #102 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> fix(feature/ujin/#102): assets 파일명 변경 및 paginationArea 수정

- shoppingmall/src/components/nav/Nav.js
- shoppingmall/src/components/sellpage/PaginationArea.js
> 페이징과 네브바 수정

- shoppingmall/src/components/myPage/Info.js
- shoppingmall/src/components/myPage/MyDealList.js
- shoppingmall/src/components/productDetails/ProductDetail.js
> ex) #107 
> 상품 정보 페이지에서 작은 화면으로 볼 때 깨지는 이슈 해결
마이페이지 판매 내역 링크 걸기
마이페이지 정보 조회 텍스트가 상자 넘어가지 않게 바꾸기
>
> [design] 상품 정보, 마이페이지 UI 수정

- shoppingmall/src/components/userAccount/Login.js
- shoppingmall/src/components/userAccount/Signup.js
> [fix] console.log 삭제

- shoppingmall/src/components/productList/ProductList.js
- shoppingmall/src/components/productwritepage/ProductComponent.js
- shoppingmall/src/components/sellpage/PaginationArea.js
> 
#113 
#111 
> 
페이지 로드 안되던 오류해결
>
> [ fix ] 메인, 판매내역 페이지 오류 해결

- shoppingmall/src/components/productDetails/ProductDetail.js
- shoppingmall/src/components/productList/ProducFilter.js
- shoppingmall/src/components/productList/ProductList.js
> 모달임포트 경로 수정

- shoppingmall/src/components/productDetails/ProductDetail.js
- shoppingmall/src/components/productList/ProducFilter.js
> 팝업창 닫히도록 코드 수정
